### ISSUE TITLE
Forge cannot download the minecraft.jar server file

### ISSUE THREAD

**Issue by James712346** [othrayte/docker-minecraft-server#2]
This is the outputted error after following your steps 
```bash
java.net.preferIPv4Stack=true`


Installing server to current directory


MESSAGE: Data kindly mirrored by Forge at http://MinecraftForge.net/


MESSAGE: Considering minecraft server jar


MESSAGE: Downloading minecraft server version 1.12.2


java.net.ConnectException: Connection refused (Connection refused)


	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)


	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)


	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)


	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)


	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)


	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)


	at java.security.AccessController.doPrivileged(Native Method)


	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)


	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)


	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)


	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)


	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:457)


	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:445)


	at com.google.common.io.ByteStreams$6.openStream(ByteStreams.java:989)


	at com.google.common.io.ByteSource.copyTo(ByteSource.java:202)


	at com.google.common.io.Files.copy(Files.java:382)


	at net.minecraftforge.installer.DownloadUtils.downloadFileEtag(DownloadUtils.java:174)


	at net.minecraftforge.installer.ServerInstall.run(ServerInstall.java:53)


	at net.minecraftforge.installer.InstallerAction.run(InstallerAction.java:43)


	at net.minecraftforge.installer.SimpleInstaller.handleOptions(SimpleInstaller.java:75)


	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:50)


	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.lang.reflect.Method.invoke(Method.java:498)


	at net.minecraftforge.installer.Java6Gate.main(Java6Gate.java:48)


Caused by: java.net.ConnectException: Connection refused (Connection refused)


	at java.net.PlainSocketImpl.socketConnect(Native Method)


	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)


	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)


	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)


	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)


	at java.net.Socket.connect(Socket.java:607)


	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)


	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)


	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)


	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)


	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)


	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)


	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)


	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)


	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)


	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)


	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)


	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)


	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3061)


	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:305)


	at net.minecraftforge.installer.DownloadUtils.downloadFileEtag(DownloadUtils.java:163)


	... 9 more


Downloading minecraft server failed, invalid e-tag checksum.


Try again, or manually place server jar to skip download.


There was an error during server installation


mv: cannot stat 'forge-*-universal.jar': No such file or directory


 ************************


 *  STARTING Minecraft  *


 ************************


Error: Unable to access jarfile forge-server.jar```

**Comment by James712346** [comment]
sorry, I forgot about my pi-hole which was blocking the connection to download the 1.12 server jar file
